export type { TerrainErrorCode } from './errors'
export { TerrainError } from './errors'
export type { CraterConfig, ReliefConfig, ResolvedWorldConfig, World, WorldConfig } from './world'
export { DEFAULT_CRATERS, DEFAULT_RELIEF, defineWorld, sampleHeights } from './world'
export type { GridCell, HeightGrid } from './grid'
export type { Chunk, ChunkCoords } from './chunk'
export { generateChunk, MASK_SEEN, MASK_TRAVERSABLE } from './chunk'
export { reachableFrom, slopeAt, traversableMask } from './analysis'
export { viewshed } from './viewshed'
export { CHUNK_FORMAT_VERSION, CHUNK_HEADER_BYTES, decodeChunk, encodeChunk } from './encode'
